### ISSUE TITLE
Set up database

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#6]
Choose database provider, create schema for database to allow for NFT cards

**Comment by ahsanwtc** [comment]
Hi, can you explain a bit about the requirement? 
I can set up an atlas mongo db collection which can then provide you with nft data (name, image, description etc) which can be pulled to populate the NFT cards. Is that be something you are looking for?

**Comment by aryamankha** [comment]
Yes! That's exactly what we're looking for. We need two separate databases, one for NFTs (name, image, description, price) and one for users (first name, last name, username, password, artist/fan, NFTs owned)

**Comment by aryamankha** [comment]
Assigning this task to you

**Comment by ahsanwtc** [comment]
ok perfect, then I'll work on it

**Comment by ahsanwtc** [comment]
There is one thing which I need your feedback is on db credentials. There are two ways:

Either I provide you with credentials and you can plug them in vercel console environment variables so the live version can access the db. Problem with this is that the local developments won't have access to them because distributing them to contributors will make them public which could be a potential threat.

OR I can set up a separate service which will have API endpoints /users and /nfts for read and write to db. Once those endpoints are working, I'll integrate it with backstage. This way, I'll keep the db credentials away from public and those endpoints can be used by anyone in any environment without compromising the db. 

What's your opinion on this?

**Comment by ahsanwtc** [comment]
for the separate service set up, I've created the API endpoints which provides users and nfts information.

https://backstage-hacktoberfest-service.vercel.app/api/users
https://backstage-hacktoberfest-service.vercel.app/api/users/id

https://backstage-hacktoberfest-service.vercel.app/api/nfts
https://backstage-hacktoberfest-service.vercel.app/api/nfts/id

if this is ok by you, I'll keep working on this solution

**Comment by aryamankha** [comment]
The separate service approach seems best - it keeps database functionality encapsulated and is a more scalable solution.

**Comment by aryamankha** [comment]
Hey @ahsanwtc - what is the progress looking like on this?

**Comment by ahsanwtc** [comment]
I have made some progress on the api, the endpoints are running but need
some fixes in bundling nft and artist data together before serving. Will
have it done soon and then add it to the project.

**Comment by ahsanwtc** [comment]
![Screenshot from 2022-10-17 15-57-41](https://user-images.githubusercontent.com/8014060/196196974-44fa1034-f729-4c2c-bbba-6e6e0ee22695.png)

I have created a pull request to add the nft information. This API can be used to pull information as needed. Unfortunately, my tailwind and typescript knowledge isn't good enough to contribute further on front side but if you want I can continue working on the backend service (adding possibility of creating records, auth for users to mutate their data etc)

**Comment by aryamankha** [comment]
We'll need to actually connect the profiles from auth0 to the database so that each user sees their own NFTs on their profile page if you want to start tackling that. Feel free to create issues for different parts of the wiring.

**Comment by ahsanwtc** [comment]
ok, i'm on it
